### ISSUE TITLE
More helpful failure message for Mac OSX

### ISSUE THREAD

**Issue by jamescheney** [kolmodin/hinotify#12]
Mac OSX doesn't provide the inotify service, so obviously this package won't install.  However, it would be nice if the failure message explained clearly that this package is Linux only rather than giving a mysterious failure message:

jcheney$ sudo cabal install hinotify --verbose
Reading available packages...
Choosing modular solver.
Resolving dependencies...
Ready to install hinotify-0.3.7
Extracting
/Users/jcheney/Library/Haskell/repo-cache/hackage.haskell.org/hinotify/0.3.7/hinotify-0.3.7.tar.gz
to /tmp/hinotify-0.3.7-53062...
Updating hinotify.cabal with the latest revision from the index.
Configuring hinotify-0.3.7...
Waiting for install task to finish...
creating /tmp/hinotify-0.3.7-53062/hinotify-0.3.7/dist/setup
creating /tmp/hinotify-0.3.7-53062/hinotify-0.3.7/dist
creating /tmp/hinotify-0.3.7-53062/hinotify-0.3.7/dist/setup
/Users/jcheney/.cabal/setup-exe-cache/setup-Cabal-1.18.1.4-x86_64-osx-ghc-7.8.3
configure --verbose=2 --ghc --prefix=/Users/jcheney/Library/Haskell
--bindir=/Users/jcheney/Library/Haskell/bin
--libdir=/Users/jcheney/Library/Haskell/ghc-7.8.3-x86_64/lib
--libsubdir=hinotify-0.3.7 --libexecdir=/Users/jcheney/Library/Haskell/libexec
--datadir=/Users/jcheney/Library/Haskell/share
--datasubdir=ghc-7.8.3-x86_64/hinotify-0.3.7
--docdir=/Users/jcheney/Library/Haskell/ghc-7.8.3-x86_64/lib/hinotify-0.3.7/doc
--htmldir=/Users/jcheney/Library/Haskell/ghc-7.8.3-x86_64/lib/hinotify-0.3.7/doc/html
--haddockdir=/Users/jcheney/Library/Haskell/ghc-7.8.3-x86_64/lib/hinotify-0.3.7/doc/html
--sysconfdir=/Users/jcheney/Library/Haskell/etc --enable-library-profiling
--user --flags=split-base --extra-prog-path=/Users/jcheney/Library/Haskell/bin
--constraint=unix ==2.7.0.1 --constraint=directory ==1.2.1.0
--constraint=containers ==0.5.5.1 --constraint=base ==4.7.0.1 --disable-tests
--disable-benchmarks
Redirecting build log to {handle:
/Users/jcheney/.cabal/logs/hinotify-0.3.7.log}
Building hinotify-0.3.7...
creating /tmp/hinotify-0.3.7-53062/hinotify-0.3.7/dist/setup
/Users/jcheney/.cabal/setup-exe-cache/setup-Cabal-1.18.1.4-x86_64-osx-ghc-7.8.3
build --verbose=2
Redirecting build log to {handle:
/Users/jcheney/.cabal/logs/hinotify-0.3.7.log}
Failed to install hinotify-0.3.7
Last 10 lines of the build log ( /Users/jcheney/.cabal/logs/hinotify-0.3.7.log ):
INotify.hsc:35:25: error: sys/inotify.h: No such file or directory
INotify.hsc: In function ‘main’:
INotify.hsc:265: error: invalid use of undefined type ‘struct inotify_event’
INotify.hsc:266: error: invalid use of undefined type ‘struct inotify_event’
INotify.hsc:267: error: invalid use of undefined type ‘struct inotify_event’
INotify.hsc:268: error: invalid use of undefined type ‘struct inotify_event’
INotify.hsc:271: error: invalid use of undefined type ‘struct inotify_event’
INotify.hsc:272: error: invalid application of ‘sizeof’ to incomplete type ‘struct inotify_event’ 
compiling dist/build/System/INotify_hsc_make.c failed (exit code 1)
command was: /usr/bin/gcc -c dist/build/System/INotify_hsc_make.c -o dist/build/System/INotify_hsc_make.o -m64 -fno-stack-protector -D__GLASGOW_HASKELL__=708 -Ddarwin_BUILD_OS=1 -Dx86_64_BUILD_ARCH=1 -Ddarwin_HOST_OS=1 -Dx86_64_HOST_ARCH=1 -I/Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/directory-1.2.1.0/include -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -I/Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/unix-2.7.0.1/include -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -I/Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/time-1.4.2/include -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -I/Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/bytestring-0.10.4.0/include -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -I/Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/base-4.7.0.1/include -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -I/Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/integer-gmp-0.5.1.0/include -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -I/Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/include -Idist/build/autogen -include dist/build/autogen/cabal_macros.h -I/Library/Frameworks/GHC.framework/Versions/7.8.3-x86_64/usr/lib/ghc-7.8.3/include/
Updating world file...
cabal: Error: some packages failed to install:
hinotify-0.3.7 failed during the building phase. The exception was:
ExitFailure 1

**Comment by kolmodin** [comment]
There's not a lot we can do here except for a few hacks.

AFAIK, we could do a conditional in the `.cabal` file,
```
   if os(linux):
    -- regular config
   else:
    ghc-options: -DNOT_LINUX
    -- dummy values for everything required
```

And then use `#error Not on Linux` in a `.hs` file to fail with an error message.

**Comment by jamescheney** [comment]
Thanks, that seems reasonable.  

I just had a quick look at the Cabal documentation, and it does talk about modeling "foreign libraries" as dependencies, so I wondered whether there is a cleaner way of doing this by specifying a dependency on Linux (or on the sys/inotify.h file) rather than mysteriously failing.  However, there doesn't seem to be much detail about the right way to go about this.

More generally, it would be nice if Cabal/Hackage knew about hard dependencies like OS-specificity, so that if (say) Alice's package depends on Bob's package that depends on hinotify that only runs on Linux, this fact was obvious on Alice's automatically project page (or an attempt to install Alice's package on a non-supported OS led to a sensible error message due to an unsatisfiable dependency), but that's not your problem.

**Comment by kolmodin** [comment]
Right, we might be able to specify the `sys/inotify.h` dependency. On other platforms than Linux this pre-compile check will fail, but it won't fail with an informative message saying that this package only works on Linux. The users will still try to compile the package, and it will still fail.

One could make a new library that on Linux depends on `hinotify` and on other platforms depended on other packages. Application writers could then depend on that package instead of directly on `hinotify`. It's outside the scope if this package though.

**Comment by kolmodin** [comment]
I've added the `sys/inotify.h` dependency in the latest 0.3.8 release. The build should fail much earlier now, complaining that the header file is missing.

**Comment by kolmodin** [comment]
See ad80b588810102979fae549114d10da2bd0b63b3.

**Comment by jamescheney** [comment]
Great,thanks.  I have no objection to this being closed.

**Comment by kolmodin** [comment]
Thanks for reporting it!
