### ISSUE TITLE
Do we want Stronger Typing?

### ISSUE THREAD

**Issue by ChristopherKing42** [kolmodin/hinotify#18]
When we do `addWatch`, we can specify what events we want to watch for. Yet, the types make so any event is possible. What if we made it stronger typing, so we only had to handle an event if it were possible. For example, any of the following would work:

Each `EventVariety` gets it own specialized `addWatch` function.
Merge `EventVariety` and `Event` into a type like `EventVariety`, but with callbacks builtin (my favorite, I think). (For example, you would have `data EventVariety = ... | Create (Bool -> FilePath -> IO ()) | Deleted (Bool -> FilePath -> IO ()) | ...`)
Type Classes
Various typing extensions from GHC (we lose hs portability)

I could probably implement it. I just want to know if we want this.

**Comment by kolmodin** [comment]
I'd like to keep this simple and not do something too complicated.
In #4 I propose to go the other direction - to remove things from the library. I think it's the wrong approach to execute an IO for each event.
