### ISSUE TITLE
hinotify 0.3.10 violates the PVP

### ISSUE THREAD

**Issue by peti** [kolmodin/hinotify#29]
Version 0.3.10 of `hinotify` introduced the use of `ByteString` instead of `String` in its API.  According to 
https://pvp.haskell.org/, that change needs a major version bump, i.e. `hinotify-0.4`. As it is now, the update breaks the builds of other packages that depend on it, like `xmobar`.

**Comment by peti** [comment]
Ping?

**Comment by kolmodin** [comment]
Oh, that's bad. Probably we'll have to remove 0.3.10 and bump to 0.4. that might also break people's code, but at least it'll be correct.

I'm AFK another 2 weeks so unfortunately I can't do anything about it right now.

**Comment by kolmodin** [comment]
I've bumped hinotify to 0.4 and marked 0.3.10 as deprecated on hackage.
Thanks for filing the bug!
